###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Nacho",
    "lastName": "Berridy",
    "email": "nachoberridy1997@gmail.com",
    "password": "062527",
    "gender": "male"
}

###
GET http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/users/id/ecbfded4-fdd2-4fbf-a9eb-39576777df2f HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/users/name/John HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "password": "062527",
    "email": "nachoberridy1997@gmail.com"
}



